### PR TITLE
API enhancement with displayall,displayimage and addcomments api

### PR DESCRIPTION
**Pull request by Rajalakshmi-Subramani**
1. GET api for "/" - display all images
2. GET api for "/:id" - display selected image
3. DELETE api for "/upload/:id" - delete the image with the selected id
4. POST api for "comment/:id - add comments for the selected image id
5. DELETE api for "comment/:id/comment_id" - delete the comments for the image for the user.

### CODE REVIEW

**Comment by punamt** [comment]
Hi Raja.. changes are good..
go ahead and merge

**Comment by punamt** [comment]
hi changes are fine

**Review by punamt — COMMENTED** [review]
change are fine

**Comment by Rajalakshmi-Subramani** [comment]
> Hi Raja.. changes are good..
> go ahead and merge

Thanks for the review Punam

**Pull request merged**
