### PR TITLE
Likes

### PR DESCRIPTION
**Pull request by cgutierrez7**
- Added like and unlike API

### CODE REVIEW

**Review by Rajalakshmi-Subramani — APPROVED** [review]
Changes looks good.I think a small change might be required for the routes.
 @route POST freeshot/image/like/:id should be @route POST freeshot/dashboard/image/like:id
@route freeshot/image/unlike/:id to freeshot/dashboard/image/unlike/:id.
Since in the server.js,the route to image.js is configured 'freeshot/dashboard'

**Comment by punamt** [comment]
hi  chris yes changes are fine

**Comment by punamt** [comment]
yes  i agree with raja

**Review by punamt — APPROVED** [review]
changes are fine

**Pull request merged**
